// StockLendingViewer ABI

export const lendingViewerAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'lending_', type: 'address', internalType: 'address' },
      { name: 'config_', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'accruedInterest',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'config',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract StockLendingConfig' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currentHealthFactor',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBorrowOffers',
    inputs: [],
    outputs: [
      {
        name: 'data',
        type: 'tuple[]',
        internalType: 'struct IStockLending.BorrowOffer[]',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'collateralToken', type: 'address', internalType: 'address' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'principalDebt', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'lastInterestTimestamp', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'interestPaid', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBorrowPositions',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'stateFilter', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
    ],
    outputs: [
      {
        name: 'data',
        type: 'tuple[]',
        internalType: 'struct IStockLending.BorrowOffer[]',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'collateralToken', type: 'address', internalType: 'address' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'principalDebt', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'lastInterestTimestamp', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'interestPaid', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBorrowerLendOffers',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'stateFilter', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
    ],
    outputs: [
      {
        name: 'data',
        type: 'tuple[]',
        internalType: 'struct IStockLending.LendOffer[]',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'categoryId', type: 'uint256', internalType: 'uint256' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLendOffers',
    inputs: [],
    outputs: [
      {
        name: 'data',
        type: 'tuple[]',
        internalType: 'struct IStockLending.LendOffer[]',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'categoryId', type: 'uint256', internalType: 'uint256' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLendPositions',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'stateFilter', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
    ],
    outputs: [
      {
        name: 'data',
        type: 'tuple[]',
        internalType: 'struct IStockLending.LendOffer[]',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'categoryId', type: 'uint256', internalType: 'uint256' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLenderLoanPositions',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'stateFilter', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
    ],
    outputs: [
      {
        name: 'data',
        type: 'tuple[]',
        internalType: 'struct IStockLending.BorrowOffer[]',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'collateralToken', type: 'address', internalType: 'address' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'principalDebt', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'lastInterestTimestamp', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'interestPaid', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLiquidationInfo',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IStockLending.LiquidationInfo',
        components: [
          { name: 'liquidatedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'collateralReturned', type: 'uint256', internalType: 'uint256' },
          { name: 'liquidator', type: 'address', internalType: 'address' },
          { name: 'collateralToken', type: 'address', internalType: 'address' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'debtRepaid', type: 'uint256', internalType: 'uint256' },
          { name: 'collateralSeized', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserLiquidations',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lending',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IStockLending' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'outstandingDebt',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
