// StockLending ABI

export const lendingAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'oracle_', type: 'address', internalType: 'address' },
      { name: 'reserveWallet_', type: 'address', internalType: 'address' },
      { name: 'config_', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'accruedInterest',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'addCollateral',
    inputs: [
      { name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'borrowOffers',
    inputs: [{ name: 'id', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IStockLending.BorrowOffer',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'collateralToken', type: 'address', internalType: 'address' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'principalDebt', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'lastInterestTimestamp', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'interestPaid', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancelBorrowOffer',
    inputs: [{ name: 'offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelLendOffer',
    inputs: [{ name: 'offerId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'collateralRiskParams',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'maxLtvBps', type: 'uint256', internalType: 'uint256' },
      { name: 'liquidationBps', type: 'uint256', internalType: 'uint256' },
      { name: 'liquidationPenaltyBps', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'config',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract StockLendingConfig' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createBorrowOffer',
    inputs: [
      { name: 'collateralToken', type: 'address', internalType: 'address' },
      { name: 'lendToken', type: 'address', internalType: 'address' },
      { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
      { name: 'duration', type: 'uint256', internalType: 'uint256' },
      { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createLendOffer',
    inputs: [
      { name: 'categoryId', type: 'uint256', internalType: 'uint256' },
      { name: 'lendToken', type: 'address', internalType: 'address' },
      { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
      { name: 'duration', type: 'uint256', internalType: 'uint256' },
      { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'currentHealthFactor',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLiquidationInfo',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IStockLending.LiquidationInfo',
        components: [
          { name: 'liquidatedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'collateralReturned', type: 'uint256', internalType: 'uint256' },
          { name: 'liquidator', type: 'address', internalType: 'address' },
          { name: 'collateralToken', type: 'address', internalType: 'address' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'debtRepaid', type: 'uint256', internalType: 'uint256' },
          { name: 'collateralSeized', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserLiquidations',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lendOffers',
    inputs: [{ name: 'id', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IStockLending.LendOffer',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'lender', type: 'address', internalType: 'address' },
          { name: 'borrower', type: 'address', internalType: 'address' },
          { name: 'categoryId', type: 'uint256', internalType: 'uint256' },
          { name: 'lendToken', type: 'address', internalType: 'address' },
          { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'loanAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'interestRateBps', type: 'uint256', internalType: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
          { name: 'duration', type: 'uint256', internalType: 'uint256' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
          { name: 'matchedAt', type: 'uint256', internalType: 'uint256' },
          { name: 'expiresAt', type: 'uint256', internalType: 'uint256' },
          { name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' },
          { name: 'state', type: 'uint8', internalType: 'enum IStockLending.OfferState' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'liquidate',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'nextBorrowOfferId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextLendOfferId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'oracle',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IPriceOracle' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'outstandingDebt',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repay',
    inputs: [
      { name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repayAll',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reserveWallet',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setOracle',
    inputs: [{ name: 'newOracle', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setReserveWallet',
    inputs: [{ name: 'newReserveWallet', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'takeBorrowOffer',
    inputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'takeLendOffer',
    inputs: [
      { name: 'lendOfferId', type: 'uint256', internalType: 'uint256' },
      { name: 'collateralToken', type: 'address', internalType: 'address' },
      { name: 'collateralAmount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateBorrowOffer',
    inputs: [
      { name: 'offerId', type: 'uint256', internalType: 'uint256' },
      { name: 'newCollateralAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'newLoanAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'newInterestRateBps', type: 'uint256', internalType: 'uint256' },
      { name: 'newDuration', type: 'uint256', internalType: 'uint256' },
      { name: 'newEarlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateLendOffer',
    inputs: [
      { name: 'offerId', type: 'uint256', internalType: 'uint256' },
      { name: 'newCategoryId', type: 'uint256', internalType: 'uint256' },
      { name: 'newLoanAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'newInterestRateBps', type: 'uint256', internalType: 'uint256' },
      { name: 'newDuration', type: 'uint256', internalType: 'uint256' },
      { name: 'newEarlyRepayFeeBps', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawCollateral',
    inputs: [
      { name: 'borrowOfferId', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'BorrowOfferCancelled',
    inputs: [{ name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BorrowOfferCreated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'borrower', type: 'address', indexed: true, internalType: 'address' },
      { name: 'collateralAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'loanAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BorrowOfferUpdated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'collateralAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'loanAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'rateBps', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'duration', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CategoryRiskUpdated',
    inputs: [
      { name: 'categoryId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'maxLtvBps', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'liquidationBps', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'liquidationPenaltyBps', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CollateralAdjusted',
    inputs: [
      { name: 'borrowId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newCollateralAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'added', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CollateralBurned',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      {
        name: 'reason',
        type: 'uint8',
        indexed: false,
        internalType: 'enum IStockLending.CollateralBurnReason',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CollateralTokenStatusUpdated',
    inputs: [
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'allowed', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LendOfferCancelled',
    inputs: [{ name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LendOfferCreated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'lender', type: 'address', indexed: true, internalType: 'address' },
      { name: 'loanAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LendOfferFundsForwarded',
    inputs: [
      { name: 'lendOfferId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'lender', type: 'address', indexed: true, internalType: 'address' },
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'reserveWallet', type: 'address', indexed: false, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'cancelled', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LendOfferUpdated',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'loanAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'rateBps', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'duration', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LendTokenStatusUpdated',
    inputs: [
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'allowed', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LoanLiquidated',
    inputs: [
      { name: 'borrowId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'liquidator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'debtRepaid', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'collateralSeized', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'collateralReturned', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'liquidatedAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LoanRepaid',
    inputs: [
      { name: 'borrowId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'payer', type: 'address', indexed: true, internalType: 'address' },
      { name: 'totalAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OffersMatched',
    inputs: [
      { name: 'borrowId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'lendId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'matcher', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OracleUpdated',
    inputs: [{ name: 'newOracle', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ReserveWalletUpdated',
    inputs: [{ name: 'newReserveWallet', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokenCategoryUpdated',
    inputs: [
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'categoryId', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'AddressZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'AmountInvalid',
    inputs: [],
  },
  {
    type: 'error',
    name: 'AmountZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'CollateralNotAllowed',
    inputs: [],
  },
  {
    type: 'error',
    name: 'CollateralZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'DurationZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'FeeTooHigh',
    inputs: [],
  },
  {
    type: 'error',
    name: 'HealthFactorLow',
    inputs: [],
  },
  {
    type: 'error',
    name: 'HealthFactorOk',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidParams',
    inputs: [],
  },
  {
    type: 'error',
    name: 'LendNotAllowed',
    inputs: [],
  },
  {
    type: 'error',
    name: 'LendState',
    inputs: [],
  },
  {
    type: 'error',
    name: 'LiquidationThresholdInvalid',
    inputs: [],
  },
  {
    type: 'error',
    name: 'LoanZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'LtvExceeded',
    inputs: [],
  },
  {
    type: 'error',
    name: 'MaxLtvInvalid',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NoDebt',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NotActive',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NotMatched',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NotOwner',
    inputs: [],
  },
  {
    type: 'error',
    name: 'OracleZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'PenaltyInvalid',
    inputs: [],
  },
  {
    type: 'error',
    name: 'PriceZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'RateZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'TokenZero',
    inputs: [],
  },
] as const;
