// StockLendingView ABI

export const lendingViewerAbi = [
  // Read Functions
  {
    inputs: [],
    name: 'lending',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getBorrowOffers',
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'borrower', type: 'address' },
          { name: 'lender', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'lendToken', type: 'address' },
          { name: 'collateralAmount', type: 'uint256' },
          { name: 'loanAmount', type: 'uint256' },
          { name: 'principalDebt', type: 'uint256' },
          { name: 'interestRateBps', type: 'uint256' },
          { name: 'duration', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'matchedAt', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'lastInterestTimestamp', type: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256' },
          { name: 'interestPaid', type: 'uint256' },
          { name: 'state', type: 'uint8' },
        ],
        name: 'data',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLendOffers',
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'lender', type: 'address' },
          { name: 'borrower', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'lendToken', type: 'address' },
          { name: 'collateralAmount', type: 'uint256' },
          { name: 'loanAmount', type: 'uint256' },
          { name: 'interestRateBps', type: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256' },
          { name: 'duration', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'matchedAt', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'borrowOfferId', type: 'uint256' },
          { name: 'state', type: 'uint8' },
        ],
        name: 'data',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'stateFilter', type: 'uint8' },
    ],
    name: 'getBorrowPositions',
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'borrower', type: 'address' },
          { name: 'lender', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'lendToken', type: 'address' },
          { name: 'collateralAmount', type: 'uint256' },
          { name: 'loanAmount', type: 'uint256' },
          { name: 'principalDebt', type: 'uint256' },
          { name: 'interestRateBps', type: 'uint256' },
          { name: 'duration', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'matchedAt', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'lastInterestTimestamp', type: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256' },
          { name: 'interestPaid', type: 'uint256' },
          { name: 'state', type: 'uint8' },
        ],
        name: 'data',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'stateFilter', type: 'uint8' },
    ],
    name: 'getLenderLoanPositions',
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'borrower', type: 'address' },
          { name: 'lender', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'lendToken', type: 'address' },
          { name: 'collateralAmount', type: 'uint256' },
          { name: 'loanAmount', type: 'uint256' },
          { name: 'principalDebt', type: 'uint256' },
          { name: 'interestRateBps', type: 'uint256' },
          { name: 'duration', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'matchedAt', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'lastInterestTimestamp', type: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256' },
          { name: 'interestPaid', type: 'uint256' },
          { name: 'state', type: 'uint8' },
        ],
        name: 'data',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'stateFilter', type: 'uint8' },
    ],
    name: 'getLendPositions',
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'lender', type: 'address' },
          { name: 'borrower', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'lendToken', type: 'address' },
          { name: 'collateralAmount', type: 'uint256' },
          { name: 'loanAmount', type: 'uint256' },
          { name: 'interestRateBps', type: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256' },
          { name: 'duration', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'matchedAt', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'borrowOfferId', type: 'uint256' },
          { name: 'state', type: 'uint8' },
        ],
        name: 'data',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'stateFilter', type: 'uint8' },
    ],
    name: 'getBorrowerLendOffers',
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'lender', type: 'address' },
          { name: 'borrower', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'lendToken', type: 'address' },
          { name: 'collateralAmount', type: 'uint256' },
          { name: 'loanAmount', type: 'uint256' },
          { name: 'interestRateBps', type: 'uint256' },
          { name: 'earlyRepayFeeBps', type: 'uint256' },
          { name: 'duration', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'matchedAt', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'borrowOfferId', type: 'uint256' },
          { name: 'state', type: 'uint8' },
        ],
        name: 'data',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

